### ISSUE TITLE
Update Mouseflow tracking code

### ISSUE THREAD

**Issue by tlewek** [mlaa/style-center#12]
@modelm Based on our discussion in last week's _Style Center_ meeting, I've updated the Mouseflow tracking code to load in the footer (rather than the Ask template): https://github.com/mlaa/style-center/commit/98f664fb2ef94152e7056d0c2d990df26a894c4a.

Let me know if this works for you and I'll remove the tracking code from individual pages in wp-admin too.

**Comment by modelm** [comment]
Deployed. Thanks!

**Comment by tlewek** [comment]
Thanks. Of course, with my permissions, removing the Mouseflow tracking code in wp-admin also stripped out the src of another <script> tag on the front page.

`<script src="//72ee041dca3242679b3ed393f44d6069.js.ubembed.com" async></script>
`
Could you restore this?

**Comment by modelm** [comment]
Done
